const PlayerActionTypes = {
    ADD_PLAYER: "ADD_PLAYER",
    UPDATE_PLAYER_NAME: "UPDATE_PLAYER_NAME",
    REMOVE_PLAYERS: "REMOVE_PLAYERS",
    UPDATE_PLAYER_ROUND_POINTS: "UPDATE_PLAYER_ROUND_POINTS"
}

export default PlayerActionTypes;