const PlayerActionTypes = {
    ADD_PLAYER: "ADD_PLAYER",
    UPDATE_PLAYER_NAME: "UPDATE_PLAYER_NAME",
    UPDATE_PLAYER_ROUND_POINTS: "UPDATE_PLAYER_ROUND_POINTS",
    UPDATE_PLAYER_PHASE: "UPDATE_PLAYER_PHASE",
    END_OF_ROUND_UPDATE: "END_OF_ROUND_UPDATE",
    NEW_ROUND_SAME_PLAYERS: "NEW_ROUND_SAME_PLAYERS"
}

export default PlayerActionTypes;